version: ~> 1.0
dist: bionic
language: python
cache:
  pip: true
  directories:
    - .tox
matrix:
  include:
    - env: PYVER=py36
      python: 3.6
    - env: PYVER=py37
      python: 3.7
    - env: PYVER=py38
      python: 3.8
install:
  - pip install poetry tox
script:
  - tox -e lint
  - tox -e $(tox -l | grep ${PYVER} | xargs echo | sed 's/ /,/g')
notifications:
  email: false
